### ISSUE TITLE
install.sh doesn't manage to install repository signing keys

### ISSUE THREAD

**Issue by DaveThw** [jon-hedgerows/raspbian#3]
Hi Jon,

I've just tried to run install.sh from your website, and it fails to install your two (new?) repository signing keys, giving the (slightly cryptic!) errors:
```
gpg: can't open `': No such file or directory
gpg: can't open `': No such file or directory
```

Further on, apt then doesn't install get-iplayer, saying:
```
WARNING: The following packages cannot be authenticated!
  get-iplayer
E: There are problems and -y was used without --force-yes
```

Hunting around the internet a bit (eg [here](https://ubuntuforums.org/showthread.php?t=1040561#post_6555441) and [here](https://answers.yahoo.com/question/index?qid=20080713045327AAAmb59)), I think the lines that install your new repository signing keys need an extra '-' at the end of each line, to tell apt-key to read from stdin - ie:
```
# install the repository signing keys used for packages.hedgerows.org.uk
# - for jon@hedgerows.org.uk
wget -qO - "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8B07C4FF0F5BFDFE" | sudo apt-key add -
# - for jon's build-bot
wget -qO - "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x0315CB6C13924333" | sudo apt-key add -
```

(I've modified a local copy of the script, and it seems to work with this change!  Could do you a Pull request if you'd like..?)

Hope that helps!  Thanks for all your work getting get-player working on a Raspberry Pi!
Cheers,
Dave

**Comment by jon-hedgerows** [comment]
oops.  that's now fixed in commit 87a0a6c

thanks for letting me know
jon
