### ISSUE TITLE
gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by Geffers** [jon-hedgerows/raspbian#4]
My mistake - No issue at all.

I had a DNS network setting wrong.

Apologies.

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Jon,

Have used your compilation on previous R-Pi installation, got Stretch now and havinga problem.

Using command line to issue commands line by line when I enter the following line;

wget -qO - "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x8B07C4FF0F5BFDFE" | sudo apt-key add -

I get --- gpg: no valid OpenPGP data found

Geffers

**Comment by jon-hedgerows** [comment]
Glad you sorted it :-)

Jon
